# Generated by Django 3.0.7 on 2020-06-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblender', '0002_auto_20200610_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
