# Generated by Django 3.0.7 on 2020-06-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsblender', '0003_article_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('imageSrc', models.URLField(editable=False, null=True)),
                ('etag', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('modified', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='imageSrc',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsblender.Feed'),
        ),
    ]
